apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-prd
  labels:
    app: backend-prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-prd
  template:
    metadata:
      labels:
        app: backend-prd
    spec:
      containers:
      - name: backend-prd
        image: mtararujs/webapp-backend:latest
        ports:
        - containerPort: 5050
