name: 'Perform deployment to Kubertnes'
description: '...'
inputs:
  deployment_name:
    descrption: '..'
    required: true
  deployment_pod_name: 
    description: '..'
    required: true
  docker_image_tag: 
    description: '..'
    required: true
runs:
  using: "composite"
  steps:
    - name: Perform rolling deployment
      run: kubectl set image ${{ inputs.deployment_name}} ${{ inputs.deployment_pod_name}}=${{ inputs.docker_image_tag }}
      shell: bash
    - name: Perform rollout restart
      run: kubectl rollout restart deployment ${{ inputs.deployment_name }}
      shell: bash