apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-prd
  labels:
    app: frontend-prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-prd
  template:
    metadata:
      labels:
        app: frontend-prd
    spec:
      containers:
      - name: frontend-prd
        image: mtararujs/webapp-frontend:latest
        ports:
        - containerPort: 80