apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-stg
  labels:
    app: frontend-stg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-stg
  template:
    metadata:
      labels:
        app: frontend-stg
    spec:
      containers:
      - name: frontend-stg
        image: mtararujs/webapp-frontend:latest
        ports:
        - containerPort: 80